matrix:
  include:

    - os: linux
      dist: xenial
      language: python
      python: '3.6'
      deploy:
          provider: pypi
          distributions: sdist
          user: mainro
          password:
              secure: "hVfpoOKXAEPmYyZUU7ruMgjR5d7lIGssgWHWAWgYOCE0TdSB8V4DcbiO1d+U9z0FO0OAt9bb/PwRnLVklCXbH9DRuwXDDh1YdFZ4GarXFn42fkIntWQQKdZb4sQ8XEbiZzR4E5hUYqxgOGwL2BZTPqziVI6so78hiWi6zTMCZnKRPLwhiN/Jpky1F4bVszerKnyBRkcpWvsXXABfSNkh9nMT1GxIhSgTyeJf2gYG0+ivyXaQOnJQq1Xau2bDM8dXCe5Wnm4NCG3bA4KmGeqREDVPW9zDYcTg591Wf9hXGLHSFsghHP+EEfeH6A1dE/nhVaDqiLvv0dYmvjbKLTsXDdOItD6SeVLahY6mVa2cxlGED4vjyEbnjD/g4EjrXEavav6Xr+GN9dAjk+NmspS9aob9A/Fbox3kHB5Mzdz/jBmZwoGpZnRU/uAQQE10KJmR0uWqik4sqGuExE62qsBwMVk5KO0FyovdslLIC5OTLlxH6SEwO1RIZJVLvOqoAz1hKiveY+we/Cwe4Kw8Oz0Zb5hgP4s+wdoyOcT7MT4Ff4+u+jtlA4SpJAiJQQGBEQc/4TJVSGutaSoXM5yThN/6OZvqx1ueNzmhmgUakzI9mcLdMhSpINdmWcHz3pI/9XDsRFqMFPTEBzVYrMLHP/MYHfGn5472JWWKNNSaNyNy93M="
          on:
              tags: true

    - os: linux
      dist: xenial
      language: python
      python: '3.7'

    - os: linux
      dist: xenial
      language: python
      python: '3.8-dev'

    - os: windows
      language: sh
      python: '3.7'
      before_install:
        - choco install python3
        - ln -s "/c/Python37/python.exe" "/c/Python37/python3.exe"
        - export PATH="/c/Python37:/c/Python37/Scripts/:$PATH"

install:
  - pip install nose
  - pip install -r requirements.txt
script: nosetests -s --verbosity=3


